In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np

df = pd.read_csv("mnist 60k train data.csv")

W1014 22:36:13.580894 17820 __init__.py:687] 

  TensorFlow's `tf-nightly` package will soon be updated to TensorFlow 2.0.

  Please upgrade your code to TensorFlow 2.0:
    * https://www.tensorflow.org/beta/guide/migration_guide

  Or install the latest stable TensorFlow 1.X release:
    * `pip install -U "tensorflow==1.*"`

  Otherwise your code may be broken by the change.

  


In [3]:
x1 = df[:30000]
x2 = df[30000:]
print(x1.head, x2.head)
y1 = x1['Label']
y2 = x2['Label']
x1 = x1.drop(['Label'], 1)
x2 = x2.drop(['Label'], 1)

<bound method NDFrame.head of        Label  f0  f1  f2  f3  f4  f5  f6  f7  f8  ...  f774  f775  f776  f777  \
0          5   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
1          0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
2          4   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
3          1   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
4          9   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
...      ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...   ...   ...   ...   ...   
29995      8   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
29996      9   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
29997      6   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
29998      7   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
29999      1   0   0   0   0   0   0   0   0   0  ...     0     0     0     0  

In [4]:
from sklearn import preprocessing
mm_scaler = preprocessing.MinMaxScaler()
x1 = mm_scaler.fit_transform(x1)
x2 = mm_scaler.fit_transform(x2)
print(x1, x2)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
from sklearn.model_selection import train_test_split as tts
x1_train, x1_test, y1_train, y1_test = tts(x1, y1 , test_size = 0.1, random_state = 0)
y1_train = y1_train.values

In [6]:
x2_train, x2_test, y2_train, y2_test = tts(x2, y2 , test_size = 0.1, random_state = 0)
y2_train = y2_train.values

In [7]:
model1 = tf.keras.models.Sequential()
#model1.add(tf.keras.layers.Flatten())
model1.add(tf.keras.layers.Dense(128, input_shape = (784,), activation='relu'))
model1.add(tf.keras.layers.Dense(128, activation='relu'))
model1.add(tf.keras.layers.Dense(10, activation='softmax'))
model1.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
          

W1014 22:36:26.696621 17820 deprecation.py:506] From C:\Users\Manish\Anaconda3\envs\tensorflow_env\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1633: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [8]:
model1.fit(x1_train, y1_train, epochs = 5)
loss, acc = model1.evaluate(x1_test, y1_test)
print(acc)
print(loss)

W1014 22:36:28.851327 17820 deprecation.py:323] From C:\Users\Manish\Anaconda3\envs\tensorflow_env\lib\site-packages\tensorflow_core\python\keras\optimizer_v2\optimizer_v2.py:468: BaseResourceVariable.constraint (from tensorflow.python.ops.resource_variable_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Apply a constraint manually following the optimizer update step.


Train on 27000 samples
Epoch 1/5
27000/27000 [==============================] - 2s 58us/sample - loss: 0.3223 - acc: 0.9063
Epoch 2/5
27000/27000 [==============================] - 2s 58us/sample - loss: 0.1359 - acc: 0.9584
Epoch 3/5
27000/27000 [==============================] - 1s 54us/sample - loss: 0.0896 - acc: 0.9722
Epoch 4/5
27000/27000 [==============================] - 1s 53us/sample - loss: 0.0656 - acc: 0.9791
Epoch 5/5
3000/3000 [==============================] - 0s 33us/sample - loss: 0.0999 - acc: 0.9757
0.97566664
0.0999169512912631


In [9]:
model2 = tf.keras.models.Sequential()
#model2.add(tf.keras.layers.Flatten())
model2.add(tf.keras.layers.Dense(128, input_shape = (784,), activation='relu'))
model2.add(tf.keras.layers.Dense(128, activation='relu'))
model2.add(tf.keras.layers.Dense(10, activation='softmax'))
model2.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [10]:
model2.fit(x2_train, y2_train, epochs = 5)
loss, acc = model2.evaluate(x2_test, y2_test)
print(acc)
print(loss)

Train on 27000 samples
Epoch 1/5
27000/27000 [==============================] - 2s 62us/sample - loss: 0.3257 - acc: 0.9068
Epoch 2/5
27000/27000 [==============================] - 2s 57us/sample - loss: 0.1348 - acc: 0.9581
Epoch 3/5
27000/27000 [==============================] - 2s 61us/sample - loss: 0.0892 - acc: 0.9725
Epoch 4/5
27000/27000 [==============================] - 2s 67us/sample - loss: 0.0658 - acc: 0.9793
Epoch 5/5
3000/3000 [==============================] - 0s 38us/sample - loss: 0.1025 - acc: 0.9717
0.9716667
0.10246782459815343


In [11]:
loss, acc = model2.evaluate(x1_test, y1_test)
print(acc)
print(loss)

3000/3000 [==============================] - 0s 32us/sample - loss: 0.1071 - acc: 0.9670
0.967
0.10709825784464677


In [12]:
test = pd.read_csv("mnist 10k test data.csv")
x_test = test.drop(['Label'], 1)
x_test = mm_scaler.fit_transform(x_test)
y_test = test['Label']

In [13]:
a1 = model1.get_weights()
print("-----------Model1 weights---------------------")
print(a1)
print()
a2 = model2.get_weights()
print("-----------Model2 weights---------------------")
print(a2)
print()
m = np.add(a1,a2)
print("-----------Add weights---------------------")
print(m)
m /= 2
print("-----------Final weights---------------------")
print(m)
model1.set_weights(m)
print(model1.evaluate(x_test, y_test))

-----------Model1 weights---------------------
[array([[ 0.04944768,  0.06249865, -0.05812635, ...,  0.03777868,
         0.02766197,  0.002144  ],
       [-0.0460473 , -0.05694501,  0.04064862, ...,  0.02498788,
        -0.06621513,  0.01536871],
       [-0.02508386,  0.06978334, -0.03790456, ...,  0.06298631,
        -0.0286641 , -0.02020576],
       ...,
       [ 0.03634347, -0.07000756,  0.02587418, ...,  0.05880401,
         0.06328862,  0.05952608],
       [-0.01339922,  0.06445948,  0.04745684, ...,  0.06996835,
        -0.00219602, -0.07071491],
       [ 0.06545343,  0.05927286,  0.0195085 , ..., -0.05194242,
        -0.01343269,  0.05984987]], dtype=float32), array([ 0.0258988 , -0.0001746 ,  0.071593  , -0.04001443,  0.00858525,
       -0.03167518,  0.01724525, -0.02222996,  0.04796739,  0.00215759,
        0.03649369,  0.00232337,  0.04602218,  0.00406988, -0.02310837,
        0.05827691,  0.01916411, -0.00118261,  0.06341866,  0.03324604,
       -0.02258959,  0.00472497,  0

10000/10000 [==============================] - 0s 36us/sample - loss: 0.9637 - acc: 0.7033
[0.9637082382202149, 0.7033]
